### ISSUE TITLE
ISSUE PLS FIXKS

### ISSUE THREAD

**Issue by Loac3** [DevMystical/AutoDankMemer#1]
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\varda\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\varda\OneDrive\Desktop\AutoDankMemer-main\AutoDankMemer.py", line 316, in on_message
    bot_message = BotMessage(message)
  File "C:\Users\varda\OneDrive\Desktop\AutoDankMemer-main\AutoDankMemer.py", line 88, in __init__
    if str(self.message.reference.message_id) in message_ids[command]:
AttributeError: 'NoneType' object has no attribute 'message_id'

PLS FIX LK)PKSAD

**Comment by DevMystical** [comment]
Resolved, thank you.
